### ISSUE TITLE
Extra headers aren't optional

### ISSUE THREAD

**Issue by mirh** [SK21/AOG_RC#11]
https://github.com/SK21/AOG_RC/blob/fe67227c4d8c57f762458e546be5b60ef9889aad/RCnano/RCnano.ino#L1-L2

Of course they wouldn't be needed when you are just using the arduino pins, and when you aren't using udp, respectively. 
(yes it's a miserably small issue since you can just delete the two lines, but still)

**Comment by SK21** [comment]
I don't believe they cause that much trouble if left included. They could be commented out if necessary.

**Comment by mirh** [comment]
I was thinking you could put the includes below the user settings, and guard them with ifs, but I guess it's a pedantic trifle.
