### ISSUE TITLE
RC4 PCB and parts lists?

### ISSUE THREAD

**Issue by ikidd** [SK21/AOG_RC#3]
I think I've looked through everything, but can't find the PCB sections and the parts lists?  Am I just blind?  In another copy of the repo I have a top level folder called RateController100 with them inside, but I was checking if there were any changes to what I have and can't find anything in the current version of the repo.

**Comment by SK21** [comment]
You can find it under releases, version 1, other files. There is no changes to rc4.



Sent from my Galaxy



-------- Original message --------

**Comment by joshwilsonfarms** [comment]
![PXL_20210401_203042259](https://user-images.githubusercontent.com/81727542/113352112-db68cf80-9309-11eb-9e9c-752ac30c60c1.jpg)
Is there anyway to incorporate rate control in to my section control system without using the PCB you have listed?

**Comment by SK21** [comment]
You would just have to change the pin assignments to match your setup.
