### ISSUE TITLE
Program is dead without AOG

### ISSUE THREAD

**Issue by mirh** [SK21/AOG_RC#6]
So.. after much tinkering (somehow, I had completely missed we are working on baud 38400) I got to read your program data inside the arduino IDE. 
The problem is I'm only getting `127,101,0,0,0,0,0,0,0,0` or `127,101,1,0,0,0,0,0,0,0` as returned values, forever. 
Do I need to use RateController to have actual feedback back?

And even then, am I supposed to do anything else besides setting simulation to off? 
I tried to connect my flow meter to either of the FlowPins (that I checked to get the correct signal with a simple code sample), but no matter what I do, calibration never senses a single count.

**Comment by SK21** [comment]
You need RateController for the ino to work. Set simulation off. If you are connecting with serial use one of the connections on the comm page. The green light should come on. 
![Capture](https://user-images.githubusercontent.com/13328609/116485073-9c199a00-a847-11eb-80eb-413a3fba339f.PNG)

Also the Mod indicator should turn green. 

On the Products/Options for the product you are using the Module ID and Sensor ID should be 0. The indicator should be green.
![Capture2](https://user-images.githubusercontent.com/13328609/116485313-26fa9480-a848-11eb-82e4-43f957f17395.PNG)

The Products/Diagnostics tab will show any flow signals as UPM Applied. The tractor will have to be moving and sections turned on. Make sure the sections widths are entered again in RateController even if they are already entered in AOG. Make sure on the tab Products/Options the sections you are using have a check mark.

On the Products/Rate tab the Sensor Counts/Unit needs to be entered. Whether you use VCN or PID press the Load Defaults button.

**Comment by mirh** [comment]
:\
Everything I had to do was opening AOG, not even the tractor moving, and it works now. 

...

I get why a lot of things requires the main program open, but why is that also "hard blocking" of UPM applied and sensor counts?

**Comment by SK21** [comment]
Yes that could be done as well.

**Comment by SK21** [comment]
Have you tried receiving the pulse counts without AOG?

**Comment by mirh** [comment]
Yes, that's what I was banging my head against in the first post.

**Comment by SK21** [comment]
See if it works now.

**Comment by mirh** [comment]
Perfect now, thanks!
